import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 16;
const AUTH_TAG_LENGTH = 16;

function getEncryptionKey(): Buffer {
  const hexKey = process.env["ENCRYPTION_KEY"];
  if (!hexKey || hexKey.length !== 64) {
    throw new Error(
      "ENCRYPTION_KEY must be a 64-character hex string (32 bytes). " +
        'Generate one with: node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"'
    );
  }
  return Buffer.from(hexKey, "hex");
}

export function encryptApiKey(rawKey: string): { encrypted: string; iv: string } {
  const key = getEncryptionKey();
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  const encrypted = Buffer.concat([cipher.update(rawKey, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();

  // Append auth tag to ciphertext
  const payload = Buffer.concat([encrypted, authTag]);

  return {
    encrypted: payload.toString("base64"),
    iv: iv.toString("base64"),
  };
}

export function decryptApiKey(encrypted: string, iv: string): string {
  const key = getEncryptionKey();
  const ivBuffer = Buffer.from(iv, "base64");
  const payload = Buffer.from(encrypted, "base64");

  // Last 16 bytes are the auth tag
  const authTag = payload.subarray(payload.length - AUTH_TAG_LENGTH);
  const ciphertext = payload.subarray(0, payload.length - AUTH_TAG_LENGTH);

  const decipher = crypto.createDecipheriv(ALGORITHM, key, ivBuffer);
  decipher.setAuthTag(authTag);

  const decrypted = Buffer.concat([decipher.update(ciphertext), decipher.final()]);
  return decrypted.toString("utf8");
}

export function validateEncryptionKey(): void {
  const hexKey = process.env["ENCRYPTION_KEY"];

  if (!hexKey || !/^[0-9a-fA-F]{64}$/.test(hexKey)) {
    const generated = crypto.randomBytes(32).toString("hex");
    const envPath = path.resolve(__dirname, "../../.env");

    // If .env exists but has a bad key, don't overwrite — tell the user
    if (hexKey) {
      console.error(
        "\nENCRYPTION_KEY in .env is invalid (must be a 64-character hex string).\n" +
          "Delete backend/.env and restart to auto-generate a valid key.\n"
      );
      process.exit(1);
    }

    // No .env or no key — generate one automatically
    const envContent =
      `# Auto-generated by AI Lab on first launch\n` +
      `ENCRYPTION_KEY=${generated}\n` +
      `PORT=3000\n` +
      `FRONTEND_ORIGIN=http://localhost:4200\n`;

    fs.writeFileSync(envPath, envContent, "utf-8");
    process.env["ENCRYPTION_KEY"] = generated;

    console.log("\n  Generated ENCRYPTION_KEY and wrote backend/.env");
    console.log("  Your API keys will be encrypted with this key.\n");
  }
}
